fix: FE-630 - bol name change
myparcelnl/constants pull request #70
Opened 2023-10-19 08:37 UTC by Vincentvanleeuwen

## Ticket 
[FE-630](https://myparcelnl.atlassian.net/browse/FE-630) - Als MyParcel wil ik de naam van Bol.com wijzigen in bol

## Description

Changed bol.com to bol.

2023-10-19 09:25 UTC, Cysword approved these changes

2023-10-23 13:07 UTC, EdieLemoine requested changes
Je pr titel komt niet door [onze regels](https://github.com/myparcelnl/developer/blob/main/DEVELOPERS.md)

Je ticket nummer mag erin, maar dit moet dan in de footer.

2023-10-23 13:07 UTC, EdieLemoine commented on src/__snapshots__/exports.spec.ts.snap
> +    "7": "bol",
Verandert de echte carrier naam in de API/database?

2023-10-25 10:05 UTC, EdieLemoine requested changes

2023-10-25 10:05 UTC, EdieLemoine commented on src/types/carrier.ts
> +  Bol = 'bol.com',
Oeps, dit is een breaking change, ik zou BolCom terug zetten onder deze, en als deprecated markeren met `will be removed in the next version` oid

2023-10-26 08:52 UTC, EdieLemoine commented on src/types/carrier.ts
> +  // @deprecated Use CarrierId.Bol instead. Will be removed in the next version
```suggestion
  // @deprecated Use CarrierId.Bol instead. Will be removed in the next major version
```

2023-10-26 08:52 UTC, EdieLemoine commented on src/types/carrier.ts
> +  // @deprecated Use CarrierName.Bol instead. Will be removed in the next version
```suggestion
  // @deprecated Use CarrierName.Bol instead. Will be removed in the next major version
```

2023-10-26 08:53 UTC, EdieLemoine approved these changes

2023-10-26 08:53 UTC, merged